# Log configuration for ml_project
version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s - [%(filename)s %(funcName)s] - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  stream_logger:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
